Calcular inversa de una matriz usando método de Gauss-Jordan

In [ ]:
import numpy as np

class GaussJordan:

    def intercambiarFilas(self, index1, index2, M): 
        M[index1],M[index2]=M[index2],M[index1]
        return M
   
    def multiplicarFila(self, k, fila, colInicial, M):
        M[fila] = k * M[fila]
        return M

    def restarFilas(self, f1, f2, M):
        M[f1] =  M[f2] - M[f1]
        return M 

    def buscarPivote(self, filas, col, M):
        indiceFila = -1
        maxNum = np.inf *-1
        for i in range(col+1, filas):
            if(M[i][col] > maxNum and M[i][col] != 0):
                indiceFila = i
                maxNum = M[i][col]
        return indiceFila

    def eliminacionGaussiana(self, f, c, M):
        # Definición de variables
        indicePiv = -1
        
        for i in range(f):
            pivote = M[i][i]
            if pivote == 0:
                indicePiv = self.buscarPivote(f, i, M) # Se implementa pivoteo parcial
                #TODO: Implementar pivoteo completo
                if indicePiv == -1:
                    print("El sistema no tiene solución")
                    exit(0)
                else:
                    M = self.intercambiarFilas(indicePiv, i, M)
                    pivote = M[i][i]
            
            for j in range(i+1, f): # Realizar la eliminación de los elementos debajo del pivote
                if M[j][i] != 0:
                    k = pivote / M[j][i]    # Multiplicador para la eliminación
                    M = self.multiplicarFila(k, j, i, M)
                    M = self.restarFilas(j, i, M)

    def GJ(self,f,c,M):
        for i in range(f):
            pivote=M[f-1-i][f-1-i]
            M[f-1-i]=M[f-1-i]/pivote
            for j in range(f-1-i):
              M[j]=M[j]-M[j][f-1-i]*M[f-1-i]

    def inversa(self,f,M):
      I=np.identity(f)
      matriz=np.concatenate((M,I),axis=1)
      return matriz

    def obtenerInversa(self,f,matriz):
      inversa=[]
      for i in range(f):
        aux=[]
        for j in range(f):
          aux.append(matriz[i][j+len(matriz)])
        inversa.append(aux)
      return inversa


def main():

  A=[[2,1,-1,8],[-3,-1,2,-11],[-2,1,2,-3]]
  M=[]
  for i in range(len(A)):
    aux=[]
    for j in range(len(A)):
      aux.append(A[i][j])
    M.append(aux)

  # Obtención de inversa
  objGJ=GaussJordan()
  matriz=objGJ.inversa(len(M),M)
  objGJ.eliminacionGaussiana(len(M),len(M[0]),matriz)
  objGJ.GJ(len(M),len(M[0]),matriz)
  inversa=objGJ.obtenerInversa(len(M),matriz)

  # Vector columna de resultados
  b=np.zeros((len(A),1))
  for i in range(len(b)):
    b[i]=A[i][-1]

  # Pasarlos a matrices de numpy para facilitar la multiplicación de matrices
  M=np.matrix(M)
  A=np.matrix(A)
  inversa=np.matrix(inversa)

  print("Matriz original:\n",A)
  print("Matriz inversa:\n",inversa)
  print("Solución:\n",inversa@b)


if __name__=="__main__":
  main()

Matriz original:
 [[  2   1  -1   8]
 [ -3  -1   2 -11]
 [ -2   1   2  -3]]
Matriz inversa:
 [[ 4.  3. -1.]
 [-2. -2.  1.]
 [ 5.  4. -1.]]
Solución:
 [[ 2.]
 [ 3.]
 [-1.]]
